CREATE TABLE llx_dolifleet_vehicule (
  rowid integer AUTO_INCREMENT PRIMARY KEY,
  date_creation datetime DEFAULT NULL,
  tms timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  vin varchar(50) DEFAULT NULL,
  entity integer NOT NULL DEFAULT 0,
  status integer NOT NULL DEFAULT 0,
  fk_vehicule_type varchar(255) DEFAULT NULL,
  fk_vehicule_mark varchar(255) DEFAULT NULL,
  immatriculation varchar(255) DEFAULT NULL,
  date_immat datetime DEFAULT NULL,
  fk_soc integer DEFAULT 0,
  date_customer_exploit datetime DEFAULT NULL,
  km double DEFAULT 0,
  km_date datetime DEFAULT NULL,
  fk_contract_type varchar(255) DEFAULT NULL,
  date_end_contract datetime DEFAULT NULL,
  import_key varchar(255) DEFAULT NULL,
  atelier varchar(255) DEFAULT NULL,
  carrosserie longtext DEFAULT NULL,
  dfol integer NOT NULL DEFAULT 0,
  essieu varchar(255) DEFAULT NULL,
  type_custom integer DEFAULT 0,
  coutm double DEFAULT 0,
  date_fin_fin datetime DEFAULT NULL,
  type_fin varchar(255) DEFAULT NULL,
  com_custom varchar(255) DEFAULT NULL,
  date_fin_loc datetime DEFAULT NULL,
  exit_data integer DEFAULT 0,
  age_veh integer DEFAULT 0,
  dim_pneu varchar(255) DEFAULT NULL,
  nb_pneu integer DEFAULT 0
)ENGINE=innodb;
